### PR TITLE
Bumps version to 0.6.3

### PR DESCRIPTION
**Pull request by dgasmith**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by Lnaden** [comment]
I guess the bot never triggered? You'll need to update the SHA hash.

**Comment by dgasmith** [comment]
For some reason no it did not. I just let the CI run, fail, and get the hash from there.

**Comment by dgasmith** [comment]
Looks like PyPI might have changed? Download link is now:
`https://files.pythonhosted.org/packages/c9/35/1de448f5c983b3dfc01117ae0de26f3508718652abae6ce31771dca29203/qcengine-0.6.3.tar.gz`

Rather than the previous style:
`https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz`

Looks like they switched over to the BLAKE2-256 hash?

**Comment by Lnaden** [comment]
Could it just be the `pypi.io/packages` gateway being down?

**Comment by dgasmith** [comment]
No, others work fine.

**Comment by dgasmith** [comment]
Well, maybe just `q` is down? Cannot get pydantic, but can get wasabi...

**Comment by Lnaden** [comment]
Yeah, looks like the `q` entry point is down. `p`,`h`, and `w` are fine, which I tested. And I was able to get pydantic just fine.

**Comment by Lnaden** [comment]
It looks like #11 finally got the bot to trigger too

**Comment by dgasmith** [comment]
Yea, but the entry point came up just a few minutes ago. Should pass after the CI goes through.

**Pull request merged**
